version: '3.4'

services:
  admindashboardapi:
    image: ${DOCKER_REGISTRY-}admindashboardapi
    build:
      context: .
      dockerfile: AdminDashboardAPI/AdminDashboardAPI/Dockerfile
    ports:
        - "8060:80"

  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/AuthenticationAPI/Dockerfile
    ports:
        - "8061:80"


  messagingapi:
    image: ${DOCKER_REGISTRY-}messagingapi
    build:
      context: .
      dockerfile: MessagingAPI/MessagingAPI/Dockerfile
    ports:
        - "8062:80"


  postsapi:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: PostsAPI/PostsAPI/Dockerfile
    ports:
        - "8063:80"

  timelineapi:
    image: ${DOCKER_REGISTRY-}timelineapi
    build:
      context: .
      dockerfile: TimelineAPI/TimelineAPI/Dockerfile
    ports:
        - "8064:80"

  userprofileapi:
    image: ${DOCKER_REGISTRY-}userprofileapi
    build:
      context: .
      dockerfile: UserProfileAPI/UserProfileAPI/Dockerfile
    ports:
        - "8065:80"

  usersdb:
    image: mariadb
    ports:
        - "3316:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - usersdata:/var/lib/mysql

  messagingdb:
    image: mariadb
    ports:
        - "3317:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - messagingdata:/var/lib/mysql

  postsdb:
    image: mariadb
    ports:
        - "3318:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - postsdata:/var/lib/mysql

  tagsdb:
    image: mariadb
    ports:
        - "3319:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - tagsdata:/var/lib/mysql

  userspma:
    depends_on: 
     - usersdb
    image: phpmyadmin/phpmyadmin  
    container_name: userspma
    restart: always
    ports:
     - '80:80'
    environment: 
     PMA_HOST: usersdb
  
  messagingpma:
    depends_on: 
     - messagingdb
    image: phpmyadmin/phpmyadmin  
    container_name: messagingpma
    restart: always
    ports:
     - '81:80'
    environment: 
     PMA_HOST: messagingdb

  postspma:
    depends_on: 
     - postsdb
    image: phpmyadmin/phpmyadmin  
    container_name: postspma
    restart: always
    ports:
     - '82:80'
    environment: 
     PMA_HOST: postsdb

  tagspma:
    depends_on: 
     - tagsdb
    image: phpmyadmin/phpmyadmin  
    container_name: tagspma
    restart: always
    ports:
     - '83:80'
    environment: 
     PMA_HOST: tagsdb
  
volumes:
 usersdata:
 postsdata:
 messagingdata:
 tagsdata: