version: '3.4'

services:
  tagapi:
    image: joshiiee7/tagapi
    build:
      context: .
      dockerfile: TagAPI/TagAPI/Dockerfile
    ports:
        - "8060:80"

  authenticationapi:
    image: joshiiee7/authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/AuthenticationAPI/Dockerfile
    ports:
        - "8061:80"

  messagingapi:
    image: joshiiee7/messagingapi
    build:
      context: .
      dockerfile: MessagingAPI/MessagingAPI/Dockerfile
    ports:
        - "8062:80"

  postsapi:
    image: joshiiee7/postsapi
    build:
      context: .
      dockerfile: PostsAPI/PostsAPI/Dockerfile
    ports:
        - "8063:80"

  timelineapi:
    image: joshiiee7/timelineapi
    build:
      context: .
      dockerfile: TimelineAPI/TimelineAPI/Dockerfile
    ports:
        - "8064:80"

  userprofileapi:
    image: joshiiee7/userprofileapi
    build:
      context: .
      dockerfile: UserProfileAPI/UserProfileAPI/Dockerfile
    ports:
        - "8065:80"

  youvidagateway:
    image: joshiiee7/youvidagateway
    build:
      context: .
      dockerfile: YouVidaGateway/YouVidaGateway/Dockerfile
    ports:
        - "8066:80"

  usersdb:
    image: mariadb
    ports:
        - "3316:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - usersdata:/var/lib/mysql

  messagingdb:
    image: mariadb
    ports:
        - "3317:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - messagingdata:/var/lib/mysql

  postsdb:
    image: mariadb
    ports:
        - "3318:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - postsdata:/var/lib/mysql

  tagsdb:
    image: mariadb
    ports:
        - "3319:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - tagsdata:/var/lib/mysql

  userspma:
    depends_on: 
     - usersdb
    image: phpmyadmin/phpmyadmin  
    container_name: userspma
    restart: always
    ports:
     - '80:80'
    environment: 
     PMA_HOST: usersdb
  
  messagingpma:
    depends_on: 
     - messagingdb
    image: phpmyadmin/phpmyadmin  
    container_name: messagingpma
    restart: always
    ports:
     - '81:80'
    environment: 
     PMA_HOST: messagingdb

  postspma:
    depends_on: 
     - postsdb
    image: phpmyadmin/phpmyadmin  
    container_name: postspma
    restart: always
    ports:
     - '82:80'
    environment: 
     PMA_HOST: postsdb

  tagspma:
    depends_on: 
     - tagsdb
    image: phpmyadmin/phpmyadmin  
    container_name: tagspma
    restart: always
    ports:
     - '83:80'
    environment: 
     PMA_HOST: tagsdb

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

volumes:
 usersdata:
 postsdata:
 messagingdata:
 tagsdata:
 rabbitmq_data:
 sonarqube_data:
 postgres_data:




