# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    
  build-and-test-AuthenticationAPI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies AuthenticationAPI
      working-directory: AuthenticationAPI/
      run: dotnet restore
      
    - name: Build AuthenticationAPI
      working-directory: AuthenticationAPI/
      run: dotnet build --no-restore -warnaserror
      
  build-and-test-TagAPI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies TagAPI
      working-directory: TagAPI/
      run: dotnet restore
      
    - name: Build TagAPI
      working-directory: TagAPI/
      run: dotnet build --no-restore -warnaserror
      
  build-and-test-MessagingAPI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies MessagingAPI
      working-directory: MessagingAPI/
      run: dotnet restore
      
    - name: Build MessagingAPI
      working-directory: MessagingAPI/
      run: dotnet build --no-restore -warnaserror
      
  build-and-test-PostsAPI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies PostsAPI
      working-directory: PostsAPI/
      run: dotnet restore
      
    - name: Build PostsAPI
      working-directory: PostsAPI/
      run: dotnet build --no-restore -warnaserror
      
  build-and-test-TimelineAPI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies TimelineAPI
      working-directory: TimelineAPI/
      run: dotnet restore
      
    - name: Build TimelineAPI
      working-directory: TimelineAPI/
      run: dotnet build --no-restore -warnaserror
      
  build-and-test-UserProfileAPI:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies UserProfileAPI
      working-directory: UserProfileAPI/
      run: dotnet restore
      
    - name: Build UserProfileAPI
      working-directory: UserProfileAPI/
      run: dotnet build --no-restore -warnaserror
